sudo: false

language: java
dist: focal


env: 
  global:
    - DISPLAY=:99.0

before_install:
  - sudo apt-get update
  - sudo apt-get xvfb
  - sh -e xvfb start
  - sleep 10 # give xvfb some time to start

jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

script:
- mvn -Pnu -Pgui clean verify

after_failure:
- find -name "*.txt" | grep -F 'surefire-reports' | xargs cat
