language: java
dist: focal

services:
  - xvfb
  
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - xvfb-run mvn -Pnu -Pgui clean verify

after_failure:
  - find -name "*.txt" | grep -F 'surefire-reports' | xargs cat
