sudo: false

language: java
dist: trusty


env: 
  global:
    - DISPLAY=:99.0

before_install:
 - sh -e /etc/init.d/xvfb start
 - sleep 10 # give xvfb some time to start
 - metacity --sm-disable --replace &
 - sleep 10 # give metacity some time to start

jdk: openjdk11

cache:
  directories:
  - $HOME/.m2

install: true

script:
- mvn -Pnu -Pgui clean verify

after_failure:
- find -name "*.txt" | grep -F 'surefire-reports' | xargs cat
