language: java
dist: focal

services:
  - xvfb
  
jdk: openjdk11

cache:
  directories:
    - $HOME/.m2

install: true

before_install:
  - sudo apt-get update
  - sudo apt-get install at-spi2-core

script:
  - mvn -Pnu -Pgui clean verify

after_failure:
  - find -name "*.txt" | grep -F 'surefire-reports' | xargs cat
